## Part 1: Explore the Data

Import the data and use Pandas to learn more about the dataset.

In [37]:
import pandas as pd

df = pd.read_csv('Resources/client_dataset.csv')

df.head()

first      last                    job               phone  \
0     Donald   Harding           Immunologist  793-904-7725x39308   
1    Tiffany     Myers        Music therapist    201.442.4543x942   
2    Shannon    Watson           Immunologist   687.737.9424x8503   
3     Nathan     Baker  Accounting technician    827-788-8123x012   
4  Christina  Schwartz           Chiropractor        265-829-3643   

                                 email  client_id  order_id  order_date  \
0     harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1    myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                swatson8146@payne.net      57113   1902144  2023-01-29   
3               bakernathan@benson.com      46554   9031802  2023-04-25   
4  christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   

   order_week  order_year         item_id     category         subcategory  \
0          17        2023  EUD29711-63-6U        decor            wall art   
1          20        2023  XDA18116-89-4A  consumables                pens   
2           4        2023  ABE59463-05-7E     software  project management   
3          17        2023  ZMM00836-65-0C  consumables                pens   
4          21        2023  BZX55559-12-3X  consumables                misc   

   unit_price  unit_cost  unit_weight  qty  line_number  
0     1096.80     762.71         7.50  105            1  
1       24.95      15.09         1.49   21            0  
2       13.52       7.86         1.68   39            6  
3       36.42      24.85         1.23   29            3  
4      195.10     108.17        46.43   20            1

In [38]:
# View the column names in the data
df.columns

Index(['first', 'last', 'job', 'phone', 'email', 'client_id', 'order_id',
       'order_date', 'order_week', 'order_year', 'item_id', 'category',
       'subcategory', 'unit_price', 'unit_cost', 'unit_weight', 'qty',
       'line_number'],
      dtype='object')

In [39]:
# Use the describe function to gather some basic statistics
df.describe()


client_id      order_id    order_week    order_year    unit_price  \
count  54639.000000  5.463900e+04  54639.000000  54639.000000  54639.000000   
mean   54837.869416  5.470190e+06     11.359139   2022.993064    136.267207   
std    25487.438231  2.599807e+06      7.023499      0.082997    183.873135   
min    10033.000000  1.000886e+06      1.000000   2022.000000      0.010000   
25%    33593.000000  3.196372e+06      6.000000   2023.000000     20.800000   
50%    53305.000000  5.496966e+06     11.000000   2023.000000     68.310000   
75%    78498.000000  7.733869e+06     17.000000   2023.000000    173.160000   
max    99984.000000  9.998480e+06     52.000000   2023.000000   1396.230000   

          unit_cost   unit_weight           qty   line_number  
count  54639.000000  54639.000000  5.463900e+04  54639.000000  
mean      99.446073      5.004116  5.702646e+02      2.979667  
std      133.164267      5.326599  1.879552e+04      2.436320  
min        0.010000      0.000000  0.000000e+00      0.000000  
25%       14.840000      1.450000  3.200000e+01      1.000000  
50%       49.890000      3.240000  6.800000e+01      3.000000  
75%      125.570000      6.890000  1.700000e+02      5.000000  
max      846.270000     46.430000  3.958244e+06      9.000000

In [40]:
# Use this space to do any additional research
# and familiarize yourself with the data.
df['category'].value_counts().head


<bound method NDFrame.head of category
consumables    23538
furniture      11915
software        8400
decor           7954
electronics     2832
Name: count, dtype: int64>

In [41]:
df.sort_values(by='qty', ascending=False)

first      last                                  job  \
21801      Julie  Anderson                  Exhibition designer   
25972        Amy   Stewart            Psychologist, educational   
8761     Randall    Watson                    Ceramics designer   
15112     Dennis   Hawkins  Social research officer, government   
50048     Amanda   Burnett                      Records manager   
...          ...       ...                                  ...   
4444      Philip     Gates                         Photographer   
21090     Daniel    Bowman                        Archaeologist   
38593      Carla   Vazquez                        Site engineer   
30396  Katherine    Hardin                  Magazine journalist   
16820      Jared    Taylor                        Haematologist   

                        phone                                email  client_id  \
21801              5933099462        anderson_better_4704@bell.biz      78965   
25972      979.793.4884x57205               stewartamy@francis.com      86721   
8761               3478635175  watson.hospital@scott-mcdonald.info      30143   
15112   001-214-888-5838x7410          hawkins.dennis.5195@lee.com      85931   
50048      (959)858-6180x6708            evidence.amanda@clark.biz      77354   
...                       ...                                  ...        ...   
4444         247.214.9743x760             gatesphilip276@foley.com      75947   
21090    001-716-757-9724x862            danielbowman@thompson.com      72892   
38593  001-908-404-5587x64031    vazquez.c.9803@santana-lewis.info      93794   
30396            229-575-6791               hardink5344@lewis.info      78465   
16820            729-249-1032                   taylorj@romero.com      37715   

       order_id  order_date  order_week  order_year         item_id  \
21801   3833568  2023-04-29          17        2023  XAE75138-91-2E   
25972   6057452  2023-03-21          12        2023  CCU49971-42-9U   
8761    3566639  2023-02-21           8        2023  XDA18116-89-4A   
15112   7263857  2023-03-05           9        2023  XXM82450-88-9M   
50048   3089707  2023-04-17          16        2023  BAB21028-35-2Z   
...         ...         ...         ...         ...             ...   
4444    1286765  2023-02-08           6        2023  UDC75479-26-5A   
21090   6514417  2023-05-17          20        2023  EZC20385-63-6E   
38593   4877398  2023-05-03          18        2023  CXD77584-10-1E   
30396   7520308  2023-02-06           6        2023  DAC03696-47-4B   
16820   4250945  2023-04-16          15        2023  BUZ87260-13-9U   

          category       subcategory  unit_price  unit_cost  unit_weight  \
21801    furniture            stands      147.66     100.11         0.09   
25972    furniture            tables      100.40      73.05         9.22   
8761   consumables              pens       24.95      15.09         1.49   
15112  consumables    paper products      323.42     183.84         2.21   
50048  consumables  kitchen supplies       81.23      69.22         6.64   
...            ...               ...         ...        ...          ...   
4444      software        accounting      277.01     174.45         4.51   
21090  electronics           cabling       96.86      74.98         0.24   
38593  consumables    paper products      253.71     160.50         4.08   
30396    furniture            stands      169.81     157.24         2.62   
16820    furniture           seating       34.02      20.43        19.89   

           qty  line_number  
21801  3958244            1  
25972   977121            3  
8761    842581            2  
15112   637318            3  
50048   494692            1  
...        ...          ...  
4444         0            2  
21090        0            6  
38593        0            4  
30396        0            6  
16820        0            0  

[54639 rows x 18 columns]

In [42]:
# What three item categories had the most entries? Answer: Consumables, furniture, software
df['category'].value_counts().head


<bound method NDFrame.head of category
consumables    23538
furniture      11915
software        8400
decor           7954
electronics     2832
Name: count, dtype: int64>

In [43]:
# For the category with the most entries,
# which subcategory had the most entries? Answer: bathroom supplies
df['subcategory'].value_counts().head


<bound method NDFrame.head of subcategory
bathroom supplies     6424
paper products        5874
kitchen supplies      5746
tables                4540
misc                  4286
stands                4201
accounting            3756
project management    3522
plants                3466
wall art              3093
seating               2664
pens                  2603
logistics             1122
telecom                978
audio visual           732
cabling                655
desks                  510
computers              467
Name: count, dtype: int64>

In [44]:
# Which five clients had the most entries in the data? The clients with the most entries were: 33615, 66037, 46820, 38378, and 24741.
most_entries = df['client_id'].value_counts()
most_entries

client_id
33615    220
66037    211
46820    209
38378    207
24741    207
        ... 
70734      4
32001      4
77583      3
76017      3
94987      1
Name: count, Length: 999, dtype: int64

In [45]:
most_entries_clients = most_entries.sort_values(ascending=False)
most_entries_clients

client_id
33615    220
66037    211
46820    209
38378    207
24741    207
        ... 
70734      4
32001      4
77583      3
76017      3
94987      1
Name: count, Length: 999, dtype: int64

In [46]:
toptop = most_entries_clients.head(5)
toptop

client_id
33615    220
66037    211
46820    209
38378    207
24741    207
Name: count, dtype: int64

In [47]:
# Store the client ids of those top 5 clients in a list.
top_clientele_df = ['33615', '66037', '46820', '38378', '24741']

In [48]:
# How many total units (the qty column) did the
# client with the most entries order order? Answer: 64,313
client_most_entries = df['client_id'].value_counts().idxmax()
client_most_entries

33615

In [49]:
clientele_data = df[df['client_id'] == client_most_entries]
total_units_ordered = clientele_data['qty'].sum()
total_units_ordered

64313

## Part 2: Transform the Data
Do we know that this client spent the more money than client 66037? If not, how would we find out? Transform the data using the steps below to prepare it for analysis.

In [50]:
# Create a column that calculates the 
# subtotal for each line using the unit_price
# and the qty
df['subtotal'] = df['unit_price']* df['qty']
df

first       last                      job               phone  \
0         Donald    Harding             Immunologist  793-904-7725x39308   
1        Tiffany      Myers          Music therapist    201.442.4543x942   
2        Shannon     Watson             Immunologist   687.737.9424x8503   
3         Nathan      Baker    Accounting technician    827-788-8123x012   
4      Christina   Schwartz             Chiropractor        265-829-3643   
...          ...        ...                      ...                 ...   
54634     Lauren      Reese           Radio producer  977.877.5272x11382   
54635    Derrick      Moore                 Musician        358.661.5483   
54636     Monica  Gutierrez         Graphic designer    294.805.9100x339   
54637      Wanda    Solomon             Toxicologist       (311)767-4924   
54638     Dwayne       Bell  Chief Financial Officer   606-619-7667x9508   

                                     email  client_id  order_id  order_date  \
0         harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1        myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                    swatson8146@payne.net      57113   1902144  2023-01-29   
3                   bakernathan@benson.com      46554   9031802  2023-04-25   
4      christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   
...                                    ...        ...       ...         ...   
54634   late_reese_4081@montoya-chavez.org      29043   9021716  2023-04-26   
54635         derrick.moore.2602@pope.info      41908   6290153  2023-02-08   
54636            gutierrezm3195@morris.org      35176   8692622  2023-03-05   
54637            solomonwanda5962@ross.org      24485   7592730  2023-01-18   
54638                     belld@galvan.com      24007   7489403  2023-01-04   

       order_week  order_year         item_id     category  \
0              17        2023  EUD29711-63-6U        decor   
1              20        2023  XDA18116-89-4A  consumables   
2               4        2023  ABE59463-05-7E     software   
3              17        2023  ZMM00836-65-0C  consumables   
4              21        2023  BZX55559-12-3X  consumables   
...           ...         ...             ...          ...   
54634          17        2023  UCA28532-31-0B     software   
54635           6        2023  EBD29277-23-7U  consumables   
54636           9        2023  EBD30093-55-9Z  consumables   
54637           3        2023  XMZ38239-49-3D    furniture   
54638           1        2023  ZCZ05589-50-5D     software   

              subcategory  unit_price  unit_cost  unit_weight   qty  \
0                wall art     1096.80     762.71         7.50   105   
1                    pens       24.95      15.09         1.49    21   
2      project management       13.52       7.86         1.68    39   
3                    pens       36.42      24.85         1.23    29   
4                    misc      195.10     108.17        46.43    20   
...                   ...         ...        ...          ...   ...   
54634           logistics       83.13      51.60         2.25    33   
54635    kitchen supplies      206.59     175.46        11.70    47   
54636   bathroom supplies       65.66      57.31         4.16   475   
54637              stands        1.48       1.22        18.04   112   
54638  project management        3.01       1.61         2.07  1031   

       line_number   subtotal  
0                1  115164.00  
1                0     523.95  
2                6     527.28  
3                3    1056.18  
4                1    3902.00  
...            ...        ...  
54634            8    2743.29  
54635            0    9709.73  
54636            6   31188.50  
54637            0     165.76  
54638            5    3103.31  

[54639 rows x 19 columns]

In [53]:
# Create a column for shipping price.
# Assume a shipping price of $7 per pound
# for orders over 50 pounds and $10 per
# pound for items 50 pounds or under.
df['shipping_price'] = df['unit_weight'].apply(lambda x: 7 if x > 50 else 10)
df

first       last                      job               phone  \
0         Donald    Harding             Immunologist  793-904-7725x39308   
1        Tiffany      Myers          Music therapist    201.442.4543x942   
2        Shannon     Watson             Immunologist   687.737.9424x8503   
3         Nathan      Baker    Accounting technician    827-788-8123x012   
4      Christina   Schwartz             Chiropractor        265-829-3643   
...          ...        ...                      ...                 ...   
54634     Lauren      Reese           Radio producer  977.877.5272x11382   
54635    Derrick      Moore                 Musician        358.661.5483   
54636     Monica  Gutierrez         Graphic designer    294.805.9100x339   
54637      Wanda    Solomon             Toxicologist       (311)767-4924   
54638     Dwayne       Bell  Chief Financial Officer   606-619-7667x9508   

                                     email  client_id  order_id  order_date  \
0         harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1        myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                    swatson8146@payne.net      57113   1902144  2023-01-29   
3                   bakernathan@benson.com      46554   9031802  2023-04-25   
4      christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   
...                                    ...        ...       ...         ...   
54634   late_reese_4081@montoya-chavez.org      29043   9021716  2023-04-26   
54635         derrick.moore.2602@pope.info      41908   6290153  2023-02-08   
54636            gutierrezm3195@morris.org      35176   8692622  2023-03-05   
54637            solomonwanda5962@ross.org      24485   7592730  2023-01-18   
54638                     belld@galvan.com      24007   7489403  2023-01-04   

       order_week  order_year  ...     category         subcategory  \
0              17        2023  ...        decor            wall art   
1              20        2023  ...  consumables                pens   
2               4        2023  ...     software  project management   
3              17        2023  ...  consumables                pens   
4              21        2023  ...  consumables                misc   
...           ...         ...  ...          ...                 ...   
54634          17        2023  ...     software           logistics   
54635           6        2023  ...  consumables    kitchen supplies   
54636           9        2023  ...  consumables   bathroom supplies   
54637           3        2023  ...    furniture              stands   
54638           1        2023  ...     software  project management   

      unit_price  unit_cost  unit_weight   qty  line_number   subtotal  \
0        1096.80     762.71         7.50   105            1  115164.00   
1          24.95      15.09         1.49    21            0     523.95   
2          13.52       7.86         1.68    39            6     527.28   
3          36.42      24.85         1.23    29            3    1056.18   
4         195.10     108.17        46.43    20            1    3902.00   
...          ...        ...          ...   ...          ...        ...   
54634      83.13      51.60         2.25    33            8    2743.29   
54635     206.59     175.46        11.70    47            0    9709.73   
54636      65.66      57.31         4.16   475            6   31188.50   
54637       1.48       1.22        18.04   112            0     165.76   
54638       3.01       1.61         2.07  1031            5    3103.31   

       shipping_price    total_price  
0                  10  125827.595000  
1                  10     583.340375  
2                  10     586.978400  
3                  10    1164.801650  
4                  10    4273.860000  
...               ...            ...  
54634              10    3007.969325  
54635              10   10618.805025  
54636              10   34084.361250  
54637            

In [54]:
# Create a column for the total price
# using the subtotal and the shipping price
# along with a sales tax of 9.25%

df['total_price'] = df['subtotal'] + df['shipping_price'] + (df['subtotal'] + df['shipping_price']) * 0.0925
df


first       last                      job               phone  \
0         Donald    Harding             Immunologist  793-904-7725x39308   
1        Tiffany      Myers          Music therapist    201.442.4543x942   
2        Shannon     Watson             Immunologist   687.737.9424x8503   
3         Nathan      Baker    Accounting technician    827-788-8123x012   
4      Christina   Schwartz             Chiropractor        265-829-3643   
...          ...        ...                      ...                 ...   
54634     Lauren      Reese           Radio producer  977.877.5272x11382   
54635    Derrick      Moore                 Musician        358.661.5483   
54636     Monica  Gutierrez         Graphic designer    294.805.9100x339   
54637      Wanda    Solomon             Toxicologist       (311)767-4924   
54638     Dwayne       Bell  Chief Financial Officer   606-619-7667x9508   

                                     email  client_id  order_id  order_date  \
0         harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1        myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                    swatson8146@payne.net      57113   1902144  2023-01-29   
3                   bakernathan@benson.com      46554   9031802  2023-04-25   
4      christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   
...                                    ...        ...       ...         ...   
54634   late_reese_4081@montoya-chavez.org      29043   9021716  2023-04-26   
54635         derrick.moore.2602@pope.info      41908   6290153  2023-02-08   
54636            gutierrezm3195@morris.org      35176   8692622  2023-03-05   
54637            solomonwanda5962@ross.org      24485   7592730  2023-01-18   
54638                     belld@galvan.com      24007   7489403  2023-01-04   

       order_week  order_year  ...     category         subcategory  \
0              17        2023  ...        decor            wall art   
1              20        2023  ...  consumables                pens   
2               4        2023  ...     software  project management   
3              17        2023  ...  consumables                pens   
4              21        2023  ...  consumables                misc   
...           ...         ...  ...          ...                 ...   
54634          17        2023  ...     software           logistics   
54635           6        2023  ...  consumables    kitchen supplies   
54636           9        2023  ...  consumables   bathroom supplies   
54637           3        2023  ...    furniture              stands   
54638           1        2023  ...     software  project management   

      unit_price  unit_cost  unit_weight   qty  line_number   subtotal  \
0        1096.80     762.71         7.50   105            1  115164.00   
1          24.95      15.09         1.49    21            0     523.95   
2          13.52       7.86         1.68    39            6     527.28   
3          36.42      24.85         1.23    29            3    1056.18   
4         195.10     108.17        46.43    20            1    3902.00   
...          ...        ...          ...   ...          ...        ...   
54634      83.13      51.60         2.25    33            8    2743.29   
54635     206.59     175.46        11.70    47            0    9709.73   
54636      65.66      57.31         4.16   475            6   31188.50   
54637       1.48       1.22        18.04   112            0     165.76   
54638       3.01       1.61         2.07  1031            5    3103.31   

       shipping_price    total_price  
0                  10  125827.595000  
1                  10     583.340375  
2                  10     586.978400  
3                  10    1164.801650  
4                  10    4273.860000  
...               ...            ...  
54634              10    3007.969325  
54635              10   10618.805025  
54636              10   34084.361250  
54637            

In [55]:
# Create a column for the cost
# of each line using unit cost, qty, and
# shipping price (assume the shipping cost
# is exactly what is charged to the client).
df['line_cost'] = df['unit_cost'] + df['shipping_price']
df

first       last                      job               phone  \
0         Donald    Harding             Immunologist  793-904-7725x39308   
1        Tiffany      Myers          Music therapist    201.442.4543x942   
2        Shannon     Watson             Immunologist   687.737.9424x8503   
3         Nathan      Baker    Accounting technician    827-788-8123x012   
4      Christina   Schwartz             Chiropractor        265-829-3643   
...          ...        ...                      ...                 ...   
54634     Lauren      Reese           Radio producer  977.877.5272x11382   
54635    Derrick      Moore                 Musician        358.661.5483   
54636     Monica  Gutierrez         Graphic designer    294.805.9100x339   
54637      Wanda    Solomon             Toxicologist       (311)767-4924   
54638     Dwayne       Bell  Chief Financial Officer   606-619-7667x9508   

                                     email  client_id  order_id  order_date  \
0         harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1        myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                    swatson8146@payne.net      57113   1902144  2023-01-29   
3                   bakernathan@benson.com      46554   9031802  2023-04-25   
4      christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   
...                                    ...        ...       ...         ...   
54634   late_reese_4081@montoya-chavez.org      29043   9021716  2023-04-26   
54635         derrick.moore.2602@pope.info      41908   6290153  2023-02-08   
54636            gutierrezm3195@morris.org      35176   8692622  2023-03-05   
54637            solomonwanda5962@ross.org      24485   7592730  2023-01-18   
54638                     belld@galvan.com      24007   7489403  2023-01-04   

       order_week  order_year  ...         subcategory unit_price unit_cost  \
0              17        2023  ...            wall art    1096.80    762.71   
1              20        2023  ...                pens      24.95     15.09   
2               4        2023  ...  project management      13.52      7.86   
3              17        2023  ...                pens      36.42     24.85   
4              21        2023  ...                misc     195.10    108.17   
...           ...         ...  ...                 ...        ...       ...   
54634          17        2023  ...           logistics      83.13     51.60   
54635           6        2023  ...    kitchen supplies     206.59    175.46   
54636           9        2023  ...   bathroom supplies      65.66     57.31   
54637           3        2023  ...              stands       1.48      1.22   
54638           1        2023  ...  project management       3.01      1.61   

       unit_weight   qty  line_number   subtotal  shipping_price  \
0             7.50   105            1  115164.00              10   
1             1.49    21            0     523.95              10   
2             1.68    39            6     527.28              10   
3             1.23    29            3    1056.18              10   
4            46.43    20            1    3902.00              10   
...            ...   ...          ...        ...             ...   
54634         2.25    33            8    2743.29              10   
54635        11.70    47            0    9709.73              10   
54636         4.16   475            6   31188.50              10   
54637        18.04   112            0     165.76              10   
54638         2.07  1031            5    3103.31              10   

         total_price  line_cost  
0      125827.595000     772.71  
1         583.340375      25.09  
2         586.978400      17.86  
3        1164.801650      34.85  
4        4273.860000     118.17  
...              ...        ...  
54634    3007.969325      61.60  
54635   10618.805025     185.46  
54636   34084.361250      67.31  
54637     192.017800      11.22  
54638    

In [56]:
# Create a column for the profit of
# each line using line cost and line price
df['profit_line'] = df['line_cost'] + df['unit_cost']
df

first       last                      job               phone  \
0         Donald    Harding             Immunologist  793-904-7725x39308   
1        Tiffany      Myers          Music therapist    201.442.4543x942   
2        Shannon     Watson             Immunologist   687.737.9424x8503   
3         Nathan      Baker    Accounting technician    827-788-8123x012   
4      Christina   Schwartz             Chiropractor        265-829-3643   
...          ...        ...                      ...                 ...   
54634     Lauren      Reese           Radio producer  977.877.5272x11382   
54635    Derrick      Moore                 Musician        358.661.5483   
54636     Monica  Gutierrez         Graphic designer    294.805.9100x339   
54637      Wanda    Solomon             Toxicologist       (311)767-4924   
54638     Dwayne       Bell  Chief Financial Officer   606-619-7667x9508   

                                     email  client_id  order_id  order_date  \
0         harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1        myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                    swatson8146@payne.net      57113   1902144  2023-01-29   
3                   bakernathan@benson.com      46554   9031802  2023-04-25   
4      christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   
...                                    ...        ...       ...         ...   
54634   late_reese_4081@montoya-chavez.org      29043   9021716  2023-04-26   
54635         derrick.moore.2602@pope.info      41908   6290153  2023-02-08   
54636            gutierrezm3195@morris.org      35176   8692622  2023-03-05   
54637            solomonwanda5962@ross.org      24485   7592730  2023-01-18   
54638                     belld@galvan.com      24007   7489403  2023-01-04   

       order_week  order_year  ... unit_price unit_cost unit_weight   qty  \
0              17        2023  ...    1096.80    762.71        7.50   105   
1              20        2023  ...      24.95     15.09        1.49    21   
2               4        2023  ...      13.52      7.86        1.68    39   
3              17        2023  ...      36.42     24.85        1.23    29   
4              21        2023  ...     195.10    108.17       46.43    20   
...           ...         ...  ...        ...       ...         ...   ...   
54634          17        2023  ...      83.13     51.60        2.25    33   
54635           6        2023  ...     206.59    175.46       11.70    47   
54636           9        2023  ...      65.66     57.31        4.16   475   
54637           3        2023  ...       1.48      1.22       18.04   112   
54638           1        2023  ...       3.01      1.61        2.07  1031   

       line_number   subtotal  shipping_price    total_price  line_cost  \
0                1  115164.00              10  125827.595000     772.71   
1                0     523.95              10     583.340375      25.09   
2                6     527.28              10     586.978400      17.86   
3                3    1056.18              10    1164.801650      34.85   
4                1    3902.00              10    4273.860000     118.17   
...            ...        ...             ...            ...        ...   
54634            8    2743.29              10    3007.969325      61.60   
54635            0    9709.73              10   10618.805025     185.46   
54636            6   31188.50              10   34084.361250      67.31   
54637            0     165.76              10     192.017800      11.22   
54638            5    3103.31              10    3401.291175      11.61   

       profit_line  
0          1535.42  
1            40.18  
2            25.72  
3            59.70  
4           226.34  
...            ...  
54634       113.20  
54635       360.92  
54636       124.62  
54637        12.44  
54638        13.22  

[54639 rows x 23 columns]

In [57]:
filtered_df = df[df['order_id'] == 2742071]
filtered_df

first   last                                       job  \
3446   Kimberly  Blair  Geographical information systems officer   
6287   Kimberly  Blair  Geographical information systems officer   
20623  Kimberly  Blair  Geographical information systems officer   
23840  Kimberly  Blair  Geographical information systems officer   
24671  Kimberly  Blair  Geographical information systems officer   
42470  Kimberly  Blair  Geographical information systems officer   

                    phone                           email  client_id  \
3446   477-680-9323x27378  blair.kimberly.6618@nelson.biz      78447   
6287   477-680-9323x27378  blair.kimberly.6618@nelson.biz      78447   
20623  477-680-9323x27378  blair.kimberly.6618@nelson.biz      78447   
23840  477-680-9323x27378  blair.kimberly.6618@nelson.biz      78447   
24671  477-680-9323x27378  blair.kimberly.6618@nelson.biz      78447   
42470  477-680-9323x27378  blair.kimberly.6618@nelson.biz      78447   

       order_id  order_date  order_week  order_year  ... unit_price unit_cost  \
3446    2742071  2023-02-27           9        2023  ...       5.59      3.05   
6287    2742071  2023-02-27           9        2023  ...     460.20    407.68   
20623   2742071  2023-02-27           9        2023  ...     135.12     80.78   
23840   2742071  2023-02-27           9        2023  ...      47.59     35.41   
24671   2742071  2023-02-27           9        2023  ...      59.69     54.86   
42470   2742071  2023-02-27           9        2023  ...      82.18     61.07   

      unit_weight  qty  line_number   subtotal  shipping_price    total_price  \
3446        10.46   77            5     430.43              10     481.169775   
6287         2.60  260            0  119652.00              10  130730.735000   
20623        2.27   12            3    1621.44              10    1782.348200   
23840        0.54   22            1    1046.98              10    1154.750650   
24671        1.57   24            2    1432.56              10    1575.996800   
42470        3.04   44            4    3615.92              10    3961.317600   

       line_cost  profit_line  
3446       13.05        16.10  
6287      417.68       825.36  
20623      90.78       171.56  
23840      45.41        80.82  
24671      64.86       119.72  
42470      71.07       132.14  

[6 rows x 23 columns]

In [58]:
filtered_df = df[df['order_id'] == 2173913]
filtered_df

first     last                 job                 phone  \
627    Darius  Stevens  Physicist, medical  +1-220-240-7019x2774   
14089  Darius  Stevens  Physicist, medical  +1-220-240-7019x2774   
14938  Darius  Stevens  Physicist, medical  +1-220-240-7019x2774   
14962  Darius  Stevens  Physicist, medical  +1-220-240-7019x2774   
22004  Darius  Stevens  Physicist, medical  +1-220-240-7019x2774   
27713  Darius  Stevens  Physicist, medical  +1-220-240-7019x2774   
53155  Darius  Stevens  Physicist, medical  +1-220-240-7019x2774   

                              email  client_id  order_id  order_date  \
627    stevensdarius@rich-leach.net      22122   2173913  2023-02-19   
14089  stevensdarius@rich-leach.net      22122   2173913  2023-02-19   
14938  stevensdarius@rich-leach.net      22122   2173913  2023-02-19   
14962  stevensdarius@rich-leach.net      22122   2173913  2023-02-19   
22004  stevensdarius@rich-leach.net      22122   2173913  2023-02-19   
27713  stevensdarius@rich-leach.net      22122   2173913  2023-02-19   
53155  stevensdarius@rich-leach.net      22122   2173913  2023-02-19   

       order_week  order_year  ... unit_price unit_cost unit_weight  qty  \
627             7        2023  ...     110.27     96.23        2.66   70   
14089           7        2023  ...       3.28      2.09        1.04   36   
14938           7        2023  ...     253.71    160.50        4.08   23   
14962           7        2023  ...      34.06     18.02        5.67   63   
22004           7        2023  ...      87.43     45.64        0.17   99   
27713           7        2023  ...      91.75     71.20        6.27   29   
53155           7        2023  ...      91.35     81.11        5.22  901   

       line_number  subtotal  shipping_price   total_price  line_cost  \
627              4   7718.90              10   8443.823250     106.23   
14089            2    118.08              10    139.927400      12.09   
14938            6   5835.33              10   6386.023025     170.50   
14962            5   2145.78              10   2355.189650      28.02   
22004            3   8655.57              10   9467.135225      55.64   
27713            1   2660.75              10   2917.794375      81.20   
53155            0  82306.35              10  89930.612375      91.11   

       profit_line  
627         202.46  
14089        14.18  
14938       331.00  
14962        46.04  
22004       101.28  
27713       152.40  
53155       172.22  

[7 rows x 23 columns]

In [59]:
filtered_df = df[df['order_id'] == 6128929]
filtered_df

first  last                       job                   phone  \
3422   Dorothy  Hall  Journalist, broadcasting  001-338-609-8495x03504   
13672  Dorothy  Hall  Journalist, broadcasting  001-338-609-8495x03504   
14517  Dorothy  Hall  Journalist, broadcasting  001-338-609-8495x03504   
16295  Dorothy  Hall  Journalist, broadcasting  001-338-609-8495x03504   
21141  Dorothy  Hall  Journalist, broadcasting  001-338-609-8495x03504   
37265  Dorothy  Hall  Journalist, broadcasting  001-338-609-8495x03504   
37949  Dorothy  Hall  Journalist, broadcasting  001-338-609-8495x03504   
38542  Dorothy  Hall  Journalist, broadcasting  001-338-609-8495x03504   
48834  Dorothy  Hall  Journalist, broadcasting  001-338-609-8495x03504   
49353  Dorothy  Hall  Journalist, broadcasting  001-338-609-8495x03504   

                                        email  client_id  order_id  \
3422   dorothy.per.1343@mitchell-chambers.com      88257   6128929   
13672  dorothy.per.1343@mitchell-chambers.com      88257   6128929   
14517  dorothy.per.1343@mitchell-chambers.com      88257   6128929   
16295  dorothy.per.1343@mitchell-chambers.com      88257   6128929   
21141  dorothy.per.1343@mitchell-chambers.com      88257   6128929   
37265  dorothy.per.1343@mitchell-chambers.com      88257   6128929   
37949  dorothy.per.1343@mitchell-chambers.com      88257   6128929   
38542  dorothy.per.1343@mitchell-chambers.com      88257   6128929   
48834  dorothy.per.1343@mitchell-chambers.com      88257   6128929   
49353  dorothy.per.1343@mitchell-chambers.com      88257   6128929   

       order_date  order_week  order_year  ... unit_price unit_cost  \
3422   2023-03-12          10        2023  ...      13.25     11.75   
13672  2023-03-12          10        2023  ...     136.49     90.12   
14517  2023-03-12          10        2023  ...     107.61     98.35   
16295  2023-03-12          10        2023  ...      78.18     42.72   
21141  2023-03-12          10        2023  ...      28.12     23.64   
37265  2023-03-12          10        2023  ...       1.63      1.14   
37949  2023-03-12          10        2023  ...     931.60    470.05   
38542  2023-03-12          10        2023  ...       6.09      5.50   
48834  2023-03-12          10        2023  ...     137.01     98.70   
49353  2023-03-12          10        2023  ...      84.96     72.54   

      unit_weight   qty  line_number   subtotal  shipping_price  \
3422         7.61   671            3    8890.75              10   
13672        7.05    40            6    5459.60              10   
14517        6.28  1089            9  117187.29              10   
16295        0.78    44            8    3439.92              10   
21141        4.60    26            2     731.12              10   
37265        6.00    45            1      73.35              10   
37949        6.55   344            0  320470.40              10   
38542        1.38     8            4      48.72              10   
48834        0.55   664            5   90974.64              10   
49353        4.26  1663            7  141288.48              10   

         total_price  line_cost  profit_line  
3422     9724.069375      21.75        33.50  
13672    5975.538000     100.12       190.24  
14517  128038.039325     108.35       206.70  
16295    3769.037600      52.72        95.44  
21141     809.673600      33.64        57.28  
37265      91.059875      11.14        12.28  
37949  350124.837000     480.05       950.10  
38542      64.151600      15.50        21.00  
48834   99400.719200     108.70       207.40  
49353  154368.589400      82.54       155.08  

[10 rows x 23 columns]

## Part 3: Confirm your work
You have email receipts showing that the total prices for 3 orders. Confirm that your calculations match the receipts. Remember, each order has multiple lines.

Order ID 2742071 had a total price of \$152,811.89

Order ID 2173913 had a total price of \$162,388.71

Order ID 6128929 had a total price of \$923,441.25


In [60]:
# Aggregate total prices by 'Order ID'
order_totals = df.groupby('order_id')['total_price'].sum()

In [61]:
# Provided receipts as a dictionary for easy access
receipts = {
    2742071: 152811.89,
    2173913: 162388.71,
    6128929: 923441.25
}

# Check if the calculated totals match the receipts
for order_id, expected_total in receipts.items():
    calculated_total = order_totals.get(order_id, 0)
    print(f"Order ID {order_id}: Calculated Total = ${calculated_total:.2f}, Receipt Total = ${expected_total:.2f}")
    print("Match:", abs(calculated_total - expected_total) < 0.01)  # Check if the totals are nearly equal


Order ID 2742071: Calculated Total = $139686.32, Receipt Total = $152811.89
Match: False
Order ID 2173913: Calculated Total = $119640.51, Receipt Total = $162388.71
Match: False
Order ID 6128929: Calculated Total = $752365.71, Receipt Total = $923441.25
Match: False


## Part 4: Summarize and Analyze
Use the new columns with confirmed values to find the following information.

In [68]:
# Aggregate total prices by 'Order ID'
client_id_totals = df.groupby('client_id')['total_price'].sum()

In [69]:
# How much did each of the top 5 clients by quantity
# spend? Check your work from Part 1 for client ids.
receipts_two = {
    33615: 8377308.52,
    66037: 10259514.79,
    46820: 9743794.36,
    38378: 12906550.87,
    24741: 82268892.02
}

# Check if the calculated totals match the receipts
for client_id, expected_total in receipts_two.items():
    calculated_total = order_totals.get(client_id, 0)
    print(f"Client ID {client_id}: Calculated Total = ${calculated_total:.2f}, Receipt Total = ${expected_total:.2f}")
    print("Match:", abs(calculated_total - expected_total) < 0.01)  # Check if the totals are nearly equal

Client ID 33615: Calculated Total = $0.00, Receipt Total = $8377308.52
Match: False
Client ID 66037: Calculated Total = $0.00, Receipt Total = $10259514.79
Match: False
Client ID 46820: Calculated Total = $0.00, Receipt Total = $9743794.36
Match: False
Client ID 38378: Calculated Total = $0.00, Receipt Total = $12906550.87
Match: False
Client ID 24741: Calculated Total = $0.00, Receipt Total = $82268892.02
Match: False


In [106]:
import pandas as pd

df = pd.read_csv('Resources/client_dataset.csv')

df.head()

first      last                    job               phone  \
0     Donald   Harding           Immunologist  793-904-7725x39308   
1    Tiffany     Myers        Music therapist    201.442.4543x942   
2    Shannon    Watson           Immunologist   687.737.9424x8503   
3     Nathan     Baker  Accounting technician    827-788-8123x012   
4  Christina  Schwartz           Chiropractor        265-829-3643   

                                 email  client_id  order_id  order_date  \
0     harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1    myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                swatson8146@payne.net      57113   1902144  2023-01-29   
3               bakernathan@benson.com      46554   9031802  2023-04-25   
4  christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   

   order_week  order_year         item_id     category         subcategory  \
0          17        2023  EUD29711-63-6U        decor            wall art   
1          20        2023  XDA18116-89-4A  consumables                pens   
2           4        2023  ABE59463-05-7E     software  project management   
3          17        2023  ZMM00836-65-0C  consumables                pens   
4          21        2023  BZX55559-12-3X  consumables                misc   

   unit_price  unit_cost  unit_weight  qty  line_number  
0     1096.80     762.71         7.50  105            1  
1       24.95      15.09         1.49   21            0  
2       13.52       7.86         1.68   39            6  
3       36.42      24.85         1.23   29            3  
4      195.10     108.17        46.43   20            1

In [107]:
df['shipping_cost'] = df['unit_price'] * df['unit_weight']
df

first       last                      job               phone  \
0         Donald    Harding             Immunologist  793-904-7725x39308   
1        Tiffany      Myers          Music therapist    201.442.4543x942   
2        Shannon     Watson             Immunologist   687.737.9424x8503   
3         Nathan      Baker    Accounting technician    827-788-8123x012   
4      Christina   Schwartz             Chiropractor        265-829-3643   
...          ...        ...                      ...                 ...   
54634     Lauren      Reese           Radio producer  977.877.5272x11382   
54635    Derrick      Moore                 Musician        358.661.5483   
54636     Monica  Gutierrez         Graphic designer    294.805.9100x339   
54637      Wanda    Solomon             Toxicologist       (311)767-4924   
54638     Dwayne       Bell  Chief Financial Officer   606-619-7667x9508   

                                     email  client_id  order_id  order_date  \
0         harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1        myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                    swatson8146@payne.net      57113   1902144  2023-01-29   
3                   bakernathan@benson.com      46554   9031802  2023-04-25   
4      christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   
...                                    ...        ...       ...         ...   
54634   late_reese_4081@montoya-chavez.org      29043   9021716  2023-04-26   
54635         derrick.moore.2602@pope.info      41908   6290153  2023-02-08   
54636            gutierrezm3195@morris.org      35176   8692622  2023-03-05   
54637            solomonwanda5962@ross.org      24485   7592730  2023-01-18   
54638                     belld@galvan.com      24007   7489403  2023-01-04   

       order_week  order_year         item_id     category  \
0              17        2023  EUD29711-63-6U        decor   
1              20        2023  XDA18116-89-4A  consumables   
2               4        2023  ABE59463-05-7E     software   
3              17        2023  ZMM00836-65-0C  consumables   
4              21        2023  BZX55559-12-3X  consumables   
...           ...         ...             ...          ...   
54634          17        2023  UCA28532-31-0B     software   
54635           6        2023  EBD29277-23-7U  consumables   
54636           9        2023  EBD30093-55-9Z  consumables   
54637           3        2023  XMZ38239-49-3D    furniture   
54638           1        2023  ZCZ05589-50-5D     software   

              subcategory  unit_price  unit_cost  unit_weight   qty  \
0                wall art     1096.80     762.71         7.50   105   
1                    pens       24.95      15.09         1.49    21   
2      project management       13.52       7.86         1.68    39   
3                    pens       36.42      24.85         1.23    29   
4                    misc      195.10     108.17        46.43    20   
...                   ...         ...        ...          ...   ...   
54634           logistics       83.13      51.60         2.25    33   
54635    kitchen supplies      206.59     175.46        11.70    47   
54636   bathroom supplies       65.66      57.31         4.16   475   
54637              stands        1.48       1.22        18.04   112   
54638  project management        3.01       1.61         2.07  1031   

       line_number  shipping_cost  
0                1      8226.0000  
1                0        37.1755  
2                6        22.7136  
3                3        44.7966  
4                1      9058.4930  
...            ...            ...  
54634            8       187.0425  
54635            0      2417.1030  
54636            6       273.1456  
54637            0        26.6992  
54638            5         6.2307  

[54639 rows x 19 columns]

In [108]:
df['revenue'] = df['unit_price'] * df['qty']
df

first       last                      job               phone  \
0         Donald    Harding             Immunologist  793-904-7725x39308   
1        Tiffany      Myers          Music therapist    201.442.4543x942   
2        Shannon     Watson             Immunologist   687.737.9424x8503   
3         Nathan      Baker    Accounting technician    827-788-8123x012   
4      Christina   Schwartz             Chiropractor        265-829-3643   
...          ...        ...                      ...                 ...   
54634     Lauren      Reese           Radio producer  977.877.5272x11382   
54635    Derrick      Moore                 Musician        358.661.5483   
54636     Monica  Gutierrez         Graphic designer    294.805.9100x339   
54637      Wanda    Solomon             Toxicologist       (311)767-4924   
54638     Dwayne       Bell  Chief Financial Officer   606-619-7667x9508   

                                     email  client_id  order_id  order_date  \
0         harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1        myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                    swatson8146@payne.net      57113   1902144  2023-01-29   
3                   bakernathan@benson.com      46554   9031802  2023-04-25   
4      christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   
...                                    ...        ...       ...         ...   
54634   late_reese_4081@montoya-chavez.org      29043   9021716  2023-04-26   
54635         derrick.moore.2602@pope.info      41908   6290153  2023-02-08   
54636            gutierrezm3195@morris.org      35176   8692622  2023-03-05   
54637            solomonwanda5962@ross.org      24485   7592730  2023-01-18   
54638                     belld@galvan.com      24007   7489403  2023-01-04   

       order_week  order_year         item_id     category  \
0              17        2023  EUD29711-63-6U        decor   
1              20        2023  XDA18116-89-4A  consumables   
2               4        2023  ABE59463-05-7E     software   
3              17        2023  ZMM00836-65-0C  consumables   
4              21        2023  BZX55559-12-3X  consumables   
...           ...         ...             ...          ...   
54634          17        2023  UCA28532-31-0B     software   
54635           6        2023  EBD29277-23-7U  consumables   
54636           9        2023  EBD30093-55-9Z  consumables   
54637           3        2023  XMZ38239-49-3D    furniture   
54638           1        2023  ZCZ05589-50-5D     software   

              subcategory  unit_price  unit_cost  unit_weight   qty  \
0                wall art     1096.80     762.71         7.50   105   
1                    pens       24.95      15.09         1.49    21   
2      project management       13.52       7.86         1.68    39   
3                    pens       36.42      24.85         1.23    29   
4                    misc      195.10     108.17        46.43    20   
...                   ...         ...        ...          ...   ...   
54634           logistics       83.13      51.60         2.25    33   
54635    kitchen supplies      206.59     175.46        11.70    47   
54636   bathroom supplies       65.66      57.31         4.16   475   
54637              stands        1.48       1.22        18.04   112   
54638  project management        3.01       1.61         2.07  1031   

       line_number  shipping_cost    revenue  
0                1      8226.0000  115164.00  
1                0        37.1755     523.95  
2                6        22.7136     527.28  
3                3        44.7966    1056.18  
4                1      9058.4930    3902.00  
...            ...            ...        ...  
54634            8       187.0425    2743.29  
54635            0      2417.1030    9709.73  
54636            6       273.1456   31188.50  
54637            0        26.6992     165.76  
54638            5         6.2307 

In [110]:
df['profit'] = df['revenue'] - df['shipping_cost']
df

first       last                      job               phone  \
0         Donald    Harding             Immunologist  793-904-7725x39308   
1        Tiffany      Myers          Music therapist    201.442.4543x942   
2        Shannon     Watson             Immunologist   687.737.9424x8503   
3         Nathan      Baker    Accounting technician    827-788-8123x012   
4      Christina   Schwartz             Chiropractor        265-829-3643   
...          ...        ...                      ...                 ...   
54634     Lauren      Reese           Radio producer  977.877.5272x11382   
54635    Derrick      Moore                 Musician        358.661.5483   
54636     Monica  Gutierrez         Graphic designer    294.805.9100x339   
54637      Wanda    Solomon             Toxicologist       (311)767-4924   
54638     Dwayne       Bell  Chief Financial Officer   606-619-7667x9508   

                                     email  client_id  order_id  order_date  \
0         harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1        myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                    swatson8146@payne.net      57113   1902144  2023-01-29   
3                   bakernathan@benson.com      46554   9031802  2023-04-25   
4      christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   
...                                    ...        ...       ...         ...   
54634   late_reese_4081@montoya-chavez.org      29043   9021716  2023-04-26   
54635         derrick.moore.2602@pope.info      41908   6290153  2023-02-08   
54636            gutierrezm3195@morris.org      35176   8692622  2023-03-05   
54637            solomonwanda5962@ross.org      24485   7592730  2023-01-18   
54638                     belld@galvan.com      24007   7489403  2023-01-04   

       order_week  order_year  ...     category         subcategory  \
0              17        2023  ...        decor            wall art   
1              20        2023  ...  consumables                pens   
2               4        2023  ...     software  project management   
3              17        2023  ...  consumables                pens   
4              21        2023  ...  consumables                misc   
...           ...         ...  ...          ...                 ...   
54634          17        2023  ...     software           logistics   
54635           6        2023  ...  consumables    kitchen supplies   
54636           9        2023  ...  consumables   bathroom supplies   
54637           3        2023  ...    furniture              stands   
54638           1        2023  ...     software  project management   

      unit_price  unit_cost  unit_weight   qty  line_number  shipping_cost  \
0        1096.80     762.71         7.50   105            1      8226.0000   
1          24.95      15.09         1.49    21            0        37.1755   
2          13.52       7.86         1.68    39            6        22.7136   
3          36.42      24.85         1.23    29            3        44.7966   
4         195.10     108.17        46.43    20            1      9058.4930   
...          ...        ...          ...   ...          ...            ...   
54634      83.13      51.60         2.25    33            8       187.0425   
54635     206.59     175.46        11.70    47            0      2417.1030   
54636      65.66      57.31         4.16   475            6       273.1456   
54637       1.48       1.22        18.04   112            0        26.6992   
54638       3.01       1.61         2.07  1031            5         6.2307   

         revenue       profit  
0      115164.00  106938.0000  
1         523.95     486.7745  
2         527.28     504.5664  
3        1056.18    1011.3834  
4        3902.00   -5156.4930  
...          ...          ...  
54634    2743.29    2556.2475  
54635    9709.73    7292.6270  
54636   31188.50   30915.3544  
54637     165.76     139.0608  
54638  

In [115]:
client_ids = [24741, 38378, 66037, 46820, 33615]

[24741, 38378, 66037, 46820, 33615]

In [116]:
select_client_ids = df[df['client_id'].isin(client_ids)]
select_client_ids

first     last                                           job  \
5        Jessica    Reyes  Production designer, theatre/television/film   
12       Jessica    Reyes  Production designer, theatre/television/film   
137        Bryan    Myers                                Chief of Staff   
214        Bryan    Myers                                Chief of Staff   
216       Angela  Everett                                     Osteopath   
...          ...      ...                                           ...   
54535     Angela  Everett                                     Osteopath   
54536     Kendra  Garrett                        Pension scheme manager   
54579  Alexandra    Young                                     Dietitian   
54589  Alexandra    Young                                     Dietitian   
54613     Kendra  Garrett                        Pension scheme manager   

                  phone                            email  client_id  order_id  \
5            5016915923         jessica.reyes@grimes.net      33615   1327730   
12           5016915923         jessica.reyes@grimes.net      33615   6059361   
137    444.233.9146x233            bmyers3696@wilson.com      46820   7109502   
214    444.233.9146x233            bmyers3696@wilson.com      46820   8967498   
216    729-620-6192x875           aeverett@rodriguez.com      66037   1203693   
...                 ...                              ...        ...       ...   
54535  729-620-6192x875           aeverett@rodriguez.com      66037   7550600   
54536      808.257.2029  garrettkendra8479@jefferson.com      24741   1886506   
54579  265-666-3155x118           ayoung9158@stevens.com      38378   8661147   
54589  265-666-3155x118           ayoung9158@stevens.com      38378   4508675   
54613      808.257.2029  garrettkendra8479@jefferson.com      24741   9114777   

       order_date  order_week  order_year  ...     category  \
5      2023-05-02          18        2023  ...        decor   
12     2023-05-16          20        2023  ...  consumables   
137    2023-05-12          19        2023  ...  consumables   
214    2023-02-06           6        2023  ...    furniture   
216    2023-04-09          14        2023  ...  consumables   
...           ...         ...         ...  ...          ...   
54535  2023-02-24           8        2023  ...        decor   
54536  2023-05-26          21        2023  ...    furniture   
54579  2023-03-09          10        2023  ...  consumables   
54589  2023-03-25          12        2023  ...     software   
54613  2023-02-13           7        2023  ...    furniture   

              subcategory unit_price  unit_cost  unit_weight  qty  \
5                  plants     172.84     154.44         2.79   78   
12         paper products     229.74     198.38        27.51  568   
137     bathroom supplies     136.13     111.47         5.65  118   
214                tables       7.98       6.26         7.05  133   
216     bathroom supplies     301.87     166.09         0.26  157   
...                   ...        ...        ...          ...  ...   
54535            wall art      16.76      10.66         7.52  108   
54536              tables      63.82      40.05         4.70  721   
54579    kitchen supplies      31.25      20.29        13.07  118   
54589  project management      52.24      38.26         0.70  685   
54613              tables      95.67      59.32        13.13   91   

       line_number  shipping_cost    revenue       profit  
5                0       482.2236   13481.52   12999.2964  
12               2      6320.1474  130492.32  124172.1726  
137              9       769.1345   16063.34   15294.2055  
214              3        56.2590    1061.34    1005.0810  
216              2        78.4862   47393.59   47315.1038  
...            ...            ...        ...          ...  
54535            2       126.0352    1810.08    1684.0448  
54536            3       299.9540   46014.22   45714.2660  
54579      

In [131]:
# Create a summary DataFrame showing the totals for the
# for the top 5 clients with the following information:
# total units purchased, total shipping price,
# total revenue, and total profit. Sort by total profit.

summary = select_client_ids.groupby('client_id').agg(
    total_units_purchased=('qty', 'sum'),
    total_shipping_price=('shipping_cost', 'sum'),
    total_revenue=('revenue', 'sum'),
    total_profit=('profit', 'sum')
)

summary_sorted = summary.sort_values('total_profit', ascending=False)

print(summary_sorted)

           total_units_purchased  total_shipping_price  total_revenue  \
client_id                                                               
24741                     239862           117085.8634    70176885.25   
38378                      73667           195298.0011     8384321.15   
66037                      43018           146014.7312     7995708.38   
46820                      75768           145091.7210     7317356.03   
33615                      64313           194843.9660     5839032.11   

           total_profit  
client_id                
24741      7.005980e+07  
38378      8.189023e+06  
66037      7.849694e+06  
46820      7.172264e+06  
33615      5.644188e+06  


In [132]:
# Create a summary DataFrame showing the totals for the
# for the top 5 clients with the following information:
# total units purchased, total shipping price,
# total revenue, and total profit. Sort by total profit.


In [133]:
# Format the data and rename the columns
# to names suitable for presentation.
# Currency should be in millions of dollars.
summary_sorted['total_shipping_price'] /= 1e6
summary_sorted['total_revenue'] /= 1e6
summary_sorted['total_profit'] /= 1e6

In [134]:
summary_sorted.rename(columns={
    'total_units_purchased': 'Total Units Purchased',
    'total_shipping_price': 'Total Shipping Price (millions)',
    'total_revenue': 'Total Revenue (millions)',
    'total_profit': 'Total Profit (millions)'
}, inplace=True)
summary_sorted

Total Units Purchased  Total Shipping Price (millions)  \
client_id                                                           
24741                     239862                         0.117086   
38378                      73667                         0.195298   
66037                      43018                         0.146015   
46820                      75768                         0.145092   
33615                      64313                         0.194844   

           Total Revenue (millions)  Total Profit (millions)  
client_id                                                     
24741                     70.176885                70.059799  
38378                      8.384321                 8.189023  
66037                      7.995708                 7.849694  
46820                      7.317356                 7.172264  
33615                      5.839032                 5.644188

In [19]:
# Sort the updated data by "Total Profit" form highest to lowest




Client ID   Units Shipping Total Revenue Total Cost Total Profit
4      24741  239862   $5.13M       $82.27M    $45.69M      $36.58M
3      38378   73667   $3.43M       $12.91M     $9.63M       $3.27M
1      66037   43018   $1.40M       $10.26M     $7.00M       $3.26M
2      46820   75768   $1.60M        $9.74M     $7.01M       $2.74M
0      33615   64313   $1.83M        $8.38M     $6.18M       $2.20M